name: so
description: A client library to communicate and exchange data with SO Platform.
version: 3.3.10
repository: https://github.com/syampillai/so

environment:
  sdk: ^3.7.0

dependencies:
  web_socket_channel: ^3.0.2
  synchronized: ^3.3.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
