name: so
description: A client library to communicate and exchange data with SO Platform.
version: 3.3.7
repository: https://github.com/syampillai/so

environment:
  sdk: ^3.3.3

dependencies:
  web_socket_channel: ^2.4.5
  synchronized: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.3
