name: so
description: A client library to communicate and exchange data with SO Platform.
version: 3.3.8
repository: https://github.com/syampillai/so

environment:
  sdk: ^3.4.0

dependencies:
  web_socket_channel: ^3.0.0
  synchronized: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
