name: so
description: A client library to communicate and exchange data with SO Platform.
version: 3.4.0
repository: https://github.com/syampillai/so

environment:
  sdk: ^3.8.1

dependencies:
  web_socket_channel: ^3.0.2
  synchronized: ^3.3.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
